/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import moodmosaic.Login;
/**
 *
 * @author Lance
 */
public class DailyJournal extends javax.swing.JFrame {

public class FinalsMoodMosaic {

    public static void main(String[] args) {
        Login LoginFrame = new Login();
        LoginFrame.setVisible (true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
    }
    
}

    public DailyJournal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        signout = new javax.swing.JButton();
        Selectmood = new javax.swing.JButton();
        DailyJournal = new javax.swing.JButton();
        Sources = new javax.swing.JButton();
        Exercises = new javax.swing.JButton();
        Moodhistory = new javax.swing.JButton();
        Progress = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(204, 204, 204,80));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 1240, 40));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204,80));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jTextField2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 1240, 40));

        jTextField3.setBackground(new java.awt.Color(204, 204, 204,80));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);
        jTextField3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 1240, 40));

        jTextField4.setBackground(new java.awt.Color(204, 204, 204,80));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setBorder(null);
        jTextField4.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 1240, 40));

        jTextField5.setBackground(new java.awt.Color(204, 204, 204,80));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(null);
        jTextField5.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 1240, 40));

        jTextField6.setBackground(new java.awt.Color(204, 204, 204,80));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(null);
        jTextField6.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 1240, 40));

        jTextField7.setBackground(new java.awt.Color(204, 204, 204,80));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setBorder(null);
        jTextField7.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 1240, 40));

        signout.setForeground(new java.awt.Color(204, 204, 204,80));
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sout_1.png"))); // NOI18N
        signout.setBorderPainted(false);
        signout.setContentAreaFilled(false);
        getContentPane().add(signout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 70, 50, 50));

        Selectmood.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        Selectmood.setForeground(new java.awt.Color(255, 255, 255));
        Selectmood.setText("Select Mood");
        Selectmood.setBorderPainted(false);
        Selectmood.setContentAreaFilled(false);
        Selectmood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectmoodActionPerformed(evt);
            }
        });
        getContentPane().add(Selectmood, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 130, 40));

        DailyJournal.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        DailyJournal.setForeground(new java.awt.Color(255, 255, 255));
        DailyJournal.setText("Daily Journal");
        DailyJournal.setBorderPainted(false);
        DailyJournal.setContentAreaFilled(false);
        DailyJournal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyJournalActionPerformed(evt);
            }
        });
        getContentPane().add(DailyJournal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 130, 40));

        Sources.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        Sources.setForeground(new java.awt.Color(255, 255, 255));
        Sources.setText("Sources");
        Sources.setBorderPainted(false);
        Sources.setContentAreaFilled(false);
        Sources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourcesActionPerformed(evt);
            }
        });
        getContentPane().add(Sources, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 130, 40));

        Exercises.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        Exercises.setForeground(new java.awt.Color(255, 255, 255));
        Exercises.setText("Exercises");
        Exercises.setBorderPainted(false);
        Exercises.setContentAreaFilled(false);
        Exercises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExercisesActionPerformed(evt);
            }
        });
        getContentPane().add(Exercises, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 130, 40));

        Moodhistory.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        Moodhistory.setForeground(new java.awt.Color(255, 255, 255));
        Moodhistory.setText("Mood History");
        Moodhistory.setBorderPainted(false);
        Moodhistory.setContentAreaFilled(false);
        Moodhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoodhistoryActionPerformed(evt);
            }
        });
        getContentPane().add(Moodhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 140, 20));

        Progress.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        Progress.setForeground(new java.awt.Color(255, 255, 255));
        Progress.setText("Progress");
        Progress.setBorderPainted(false);
        Progress.setContentAreaFilled(false);
        Progress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgressActionPerformed(evt);
            }
        });
        getContentPane().add(Progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 140, 20));

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 83, 240, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dailyjournal.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1394, 804));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void SelectmoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectmoodActionPerformed
        // TODO add your handling code here:
        Selectmood SelectmoodFrame = new Selectmood();
        SelectmoodFrame.setVisible (true);
        SelectmoodFrame.pack();
        SelectmoodFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SelectmoodActionPerformed

    private void DailyJournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyJournalActionPerformed
        // TODO add your handling code here:
        DailyJournal DailyJournalFrame = new DailyJournal();
        DailyJournalFrame.setVisible (true);
        DailyJournalFrame.pack();
        DailyJournalFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_DailyJournalActionPerformed

    private void SourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourcesActionPerformed
        // TODO add your handling code here:
        Sources SourcesFrame = new Sources();
        SourcesFrame.setVisible (true);
        SourcesFrame.pack();
        SourcesFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SourcesActionPerformed

    private void ExercisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExercisesActionPerformed
        // TODO add your handling code here:
        Exercises ExercisesFrame = new Exercises();
        ExercisesFrame.setVisible (true);
        ExercisesFrame.pack();
        ExercisesFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ExercisesActionPerformed

    private void MoodhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoodhistoryActionPerformed

        MoodHistory MoodHistoryFrame = new MoodHistory();
        MoodHistoryFrame.setVisible (true);
        MoodHistoryFrame.pack();
        MoodHistoryFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_MoodhistoryActionPerformed

    private void ProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgressActionPerformed
        // TODO add your handling code here:
        Progress ProgressFrame = new Progress();
        ProgressFrame.setVisible (true);
        ProgressFrame.pack();
        ProgressFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ProgressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dailyreminder DailyreminderFrame = new Dailyreminder();
        DailyreminderFrame.setVisible (true);
        DailyreminderFrame.pack();
        DailyreminderFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DailyJournal;
    private javax.swing.JButton Exercises;
    private javax.swing.JButton Moodhistory;
    private javax.swing.JButton Progress;
    private javax.swing.JButton Selectmood;
    private javax.swing.JButton Sources;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton signout;
    // End of variables declaration//GEN-END:variables
}
